### ISSUE TITLE
Concurrency and runtime

### ISSUE THREAD

**Issue by gauteh** [aslamplr/warp_lambda#1]
Hi, this looks very interesting! Looking forward to testing. I have a conceptual AWS question:

First, it seems like AWS enforces one event per instance. `warp_lambda` starts a `tokio` multi-thread runtime which runs the warp-filter. Is it meaningful to focus on async in a lambda function? There will only ever be one request, so it might as well be blocking? Unless maybe we have to do say multiple requests for remote resources and can await them simultaneously? 

Is tower underlying the aws-lambda-runtime anyway? In that case is there two layers of tokio-runtime?

**Comment by aslamplr** [comment]
> First, it seems like AWS enforces one event per instance. warp_lambda starts a tokio multi-thread runtime which runs the warp-filter. Is it meaningful to focus on async in a lambda function? There will only ever be one request, so it might as well be blocking? Unless maybe we have to do say multiple requests for remote resources and can await them simultaneously?

Short answer: Yes, it is since aws lambda instances are re-used for events if there is an instance already spawned. 

> _To improve performance, AWS Lambda may choose to retain an instance of your function and reuse it to serve a subsequent request, rather than creating a new copy._ ([From AWS Lambda FAQ](https://aws.amazon.com/lambda/faqs/))

The following article might provide some insight into how much time the instance stays up (this information might be outdated, but the concept remains the same though). [How long does AWS Lambda keep your idle functions around before a cold start?](https://read.acloud.guru/how-long-does-aws-lambda-keep-your-idle-functions-around-before-a-cold-start-bf715d3b810)

> Is tower underlying the aws-lambda-runtime anyway? In that case is there two layers of tokio-runtime?

The `aws-lambda-runtime` provides `Handler` trait for us to implement handlers for the runtime (this crate is one such) which is similar to the Tower service trait but isn't a tower service (this is based on the revision of `aws-lambda-runtime` being used by this crate). And there is going to be only one tokio runtime ideally.

Let me know if you have more questions, happy to help.

**Comment by aslamplr** [comment]
Please re-open if required.

**Comment by gauteh** [comment]
Thanks a lot for taking the time to answer.

> > First, it seems like AWS enforces one event per instance. warp_lambda starts a tokio multi-thread runtime which runs the warp-filter. Is it meaningful to focus on async in a lambda function? There will only ever be one request, so it might as well be blocking? Unless maybe we have to do say multiple requests for remote resources and can await them simultaneously?
> 
> Short answer: Yes, it is since aws lambda instances are re-used for events if there is an instance already spawned.
> 

Thanks, reading [some docs](https://docs.aws.amazon.com/lambda/latest/dg/invocation-scaling.html) on function scaling it seems that the same instance will never process two requests concurrently, but it will be kept around for some time and re-used if a new requests is received. That means that there is not much point in writing async code across requests, but might be worth it internally if say making several database-calls concurrently.

**Comment by aslamplr** [comment]
@gauteh Thank you for the explanation.

From my testing (not sufficient enough to confirm this), an AWS Lambda function implemented with this crate. And invoked by events from an AWS API Gateway with HTTP API.  Which has a POST endpoint that receives a JSON payload from the request body (serde deserialisation), few simple validations later it writes a document to DynamoDB. And we tested the endpoint for load testing and concurrent requests as well. We never saw a multiple instance getting spawned. Whenever there is a new instance spawned we could see `Init Duration: xx.xx ms` being reported in the CloudWatch logs (I am not sure, this alone can be an indicator that a new instance is spawned).

And once again thank you for creating this issue.

**Comment by gauteh** [comment]
Interesting, could the burst still be handled sequentially by the 27 instances? But each quickly enough dispatched that it is not necessary to spawn new? I guess that depends on other tweaks in lamba, or latency before the request reaches the instances. Either way I see benefits to having everything run in async context, but if requests are never processed concurrently on same instance some async code can be switched for sync versions and there might be some less overhead and context-switching. Especially, file reads which are dispatched to a blocking thread pool, that might be noticable.

**Comment by aslamplr** [comment]
You are right, my setup is not ideal. And there might be latencies involved.

**Comment by gauteh** [comment]
Thanks for the discussion, I understand much more now. I think lambdas might be a poor choice for my application. I want to stream http responses of something similar to rest. I suspect lambdas need to have entire response constructed before returned through gateway.
